/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import model.Customer;
import controller.CustomerDAO;
import controller.StationDAO;
import controller.TicketDAO;
import controller.TrainRideDAO;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.Ticket;
import model.Station;
import model.TrainRide;
import model.Employee;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import java.time.LocalDate;


/**
 *
 * @author Delar
 */
public class CustomerMainFrm extends javax.swing.JFrame implements ActionListener{

    /**
     * Creates new form CustomerMainFrm 
     */
    CustomerMainFrm mainFrm = this;
    Customer customer;
    ArrayList<Ticket>  listTicketedCustomer;
    LocalDate startDate ;
    LocalDate endDate ;
    
    ArrayList<Station> stations;
    ArrayList<TrainRide> trainRides;
    
    public CustomerMainFrm(Customer c) {
        initComponents();
        customer = c;
        
        txtFullname.setText(c.getFullname());
        txtFullname.setEditable(false);
        
        txtAddress.setText(c.getAddress());
        txtAddress.setEditable(false);
        
        txtPhoneNumber.setText(c.getPhoneNumber());
        txtPhoneNumber.setEditable(false);
        
        txtUsername.setText(c.getUsername());
        txtUsername.setEditable(false);
        
        
        txtPassword.setVisible(false);
        lblPassword.setVisible(false);

        txtNewPassword.setVisible(false);
        lblNewPassword.setVisible(false);
        
        btnCancelEditInfo.setVisible(false);
        btnCancelEditPassword.setVisible(false);
        
        jLabel5.setVisible(false);
        jLabel6.setVisible(false);
        btnSearchTicket.setVisible(false);
        
        btnBackStartTime.setVisible(false);
        txtStartTime.setVisible(false);
        btnNextStartTime.setVisible(false);
        
        btnBackEndTime.setVisible(false);
        txtEndTime.setVisible(false);
        btnNextEndTime.setVisible(false);
        
        txtStartTime.setEditable(false);
        txtEndTime.setEditable(false);
        
        tblTicketedCustomer.getTableHeader().setReorderingAllowed(false);

        
        btnEditInfo.addActionListener(this);
        btnCancelEditInfo.addActionListener(this);
        btnEditPass.addActionListener(this);
        btnCancelEditPassword.addActionListener(this);
        btnViewTicket.addActionListener(this);
        btnSearchTicket.addActionListener(this);
        btnBackStartTime.addActionListener(this);
        btnNextStartTime.addActionListener(this);
        btnBackEndTime.addActionListener(this);
        btnNextEndTime.addActionListener(this);
        btnSreach.addActionListener(this);
        
        StationDAO stationDAO = new StationDAO();
        stations = stationDAO.getAllStation();
        
        
        cbbStartStation.removeAllItems();
        
        for( int i = 0; i< stations.size(); i++){
            Station station = stations.get(i);
            
            if (station.getId().contains("HN")){
                cbbStartStation.addItem(station.getName().trim());
            }
        }
        
        cbbEndStation.removeAllItems();
        
        for( int i = 0; i< stations.size(); i++){
            Station station = stations.get(i);
            
            if (station.getId().contains("HN")){
                cbbEndStation.addItem(station.getName().trim());
            }
        }
        
        lblNameCustomer.setText(customer.getFullname());
        lblNameCustomer.setSize(lblNameCustomer.getPreferredSize());
        
        tblTrainRide.getTableHeader().setReorderingAllowed(false);
        
        

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDesktopPane1 = new javax.swing.JDesktopPane();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jDesktopPane3 = new javax.swing.JDesktopPane();
        jPanel3 = new javax.swing.JPanel();
        lblStartBranch = new javax.swing.JLabel();
        lblEndBranch = new javax.swing.JLabel();
        lblNameCustomer = new javax.swing.JLabel();
        cbbStartBranch = new javax.swing.JComboBox<>();
        cbbEndBranch = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        cbbStartStation = new javax.swing.JComboBox<>();
        cbbEndStation = new javax.swing.JComboBox<>();
        jLabel9 = new javax.swing.JLabel();
        cbbseatType = new javax.swing.JComboBox<>();
        btnSreach = new javax.swing.JButton();
        btnAddTicket = new javax.swing.JButton();
        jPanel6 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tblTrainRide = new javax.swing.JTable();
        jPanel4 = new javax.swing.JPanel();
        jDesktopPane2 = new javax.swing.JDesktopPane();
        jPanel5 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        lblusername = new javax.swing.JLabel();
        lblPassword = new javax.swing.JLabel();
        lblNewPassword = new javax.swing.JLabel();
        btnSignOut = new javax.swing.JButton();
        txtPassword = new javax.swing.JPasswordField();
        txtNewPassword = new javax.swing.JPasswordField();
        txtUsername = new javax.swing.JTextField();
        txtFullname = new javax.swing.JTextField();
        btnEditInfo = new javax.swing.JButton();
        btnEditPass = new javax.swing.JButton();
        txtPhoneNumber = new javax.swing.JTextField();
        txtAddress = new javax.swing.JTextField();
        btnCancelEditPassword = new javax.swing.JButton();
        btnCancelEditInfo = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        btnViewTicket = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        btnSearchTicket = new javax.swing.JButton();
        btnNextStartTime = new javax.swing.JButton();
        txtEndTime = new javax.swing.JTextField();
        btnBackEndTime = new javax.swing.JButton();
        btnBackStartTime = new javax.swing.JButton();
        txtStartTime = new javax.swing.JTextField();
        btnNextEndTime = new javax.swing.JButton();
        jScrollPane4 = new javax.swing.JScrollPane();
        tblTicketedCustomer = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTabbedPane1.setFont(new java.awt.Font("Serif", 0, 14)); // NOI18N

        lblStartBranch.setFont(new java.awt.Font("Serif", 0, 14)); // NOI18N
        lblStartBranch.setText("Điểm xuất phát");

        lblEndBranch.setFont(new java.awt.Font("Serif", 0, 14)); // NOI18N
        lblEndBranch.setText("Điểm kết thúc");

        lblNameCustomer.setFont(new java.awt.Font("Serif", 0, 18)); // NOI18N
        lblNameCustomer.setText("Nguyễn Minh Thắng");

        cbbStartBranch.setFont(new java.awt.Font("Serif", 0, 12)); // NOI18N
        cbbStartBranch.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Hà Nội", "Hải Phòng", "Đà Nẵng", "Hồ Chí Minh" }));
        cbbStartBranch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbbStartBranchActionPerformed(evt);
            }
        });

        cbbEndBranch.setFont(new java.awt.Font("Serif", 0, 12)); // NOI18N
        cbbEndBranch.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Hà Nội", "Hải Phòng", "Đà Nẵng", "Hồ Chí Minh" }));
        cbbEndBranch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbbEndBranchActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Serif", 0, 14)); // NOI18N
        jLabel7.setText("Ga xuất phát");

        jLabel8.setFont(new java.awt.Font("Serif", 0, 14)); // NOI18N
        jLabel8.setText("Ga kết thúc");

        cbbStartStation.setFont(new java.awt.Font("Serif", 0, 12)); // NOI18N
        cbbStartStation.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbbStartStationActionPerformed(evt);
            }
        });

        cbbEndStation.setFont(new java.awt.Font("Serif", 0, 12)); // NOI18N
        cbbEndStation.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbbEndStationActionPerformed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Serif", 0, 14)); // NOI18N
        jLabel9.setText("Loại ghế");

        cbbseatType.setFont(new java.awt.Font("Serif", 0, 12)); // NOI18N
        cbbseatType.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Hạng 1", "Hạng 2" }));
        cbbseatType.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbbseatTypeActionPerformed(evt);
            }
        });

        btnSreach.setFont(new java.awt.Font("Serif", 0, 12)); // NOI18N
        btnSreach.setText("Tìm kiếm");
        btnSreach.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSreachActionPerformed(evt);
            }
        });

        btnAddTicket.setFont(new java.awt.Font("Serif", 3, 24)); // NOI18N
        btnAddTicket.setText("Đặt vé");
        btnAddTicket.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddTicketActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(53, 53, 53)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblEndBranch, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblStartBranch))
                .addGap(42, 42, 42)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(cbbStartBranch, 0, 99, Short.MAX_VALUE)
                    .addComponent(cbbEndBranch, 0, 99, Short.MAX_VALUE)
                    .addComponent(cbbseatType, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(87, 87, 87)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(54, 54, 54)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(cbbEndStation, 0, 120, Short.MAX_VALUE)
                            .addComponent(cbbStartStation, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addComponent(btnSreach, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 93, Short.MAX_VALUE)
                .addComponent(btnAddTicket, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(49, 49, 49))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblNameCustomer, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbbStartBranch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7)
                    .addComponent(cbbStartStation, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblStartBranch, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(cbbEndBranch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lblEndBranch))
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel8)
                        .addComponent(cbbEndStation, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(26, 26, 26)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSreach)
                    .addComponent(cbbseatType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9))
                .addContainerGap(43, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblNameCustomer)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnAddTicket, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(41, 41, 41))
        );

        tblTrainRide.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Mã tàu", "Ga xuất phát", "Ga kết thúc", "Thời gian khởi hành", "Thời gian đến", "Loại vé", "Giá vé"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane3.setViewportView(tblTrainRide);
        if (tblTrainRide.getColumnModel().getColumnCount() > 0) {
            tblTrainRide.getColumnModel().getColumn(0).setResizable(false);
            tblTrainRide.getColumnModel().getColumn(0).setPreferredWidth(25);
        }

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 900, Short.MAX_VALUE)
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 351, Short.MAX_VALUE)
        );

        jDesktopPane3.setLayer(jPanel3, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane3.setLayer(jPanel6, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jDesktopPane3Layout = new javax.swing.GroupLayout(jDesktopPane3);
        jDesktopPane3.setLayout(jDesktopPane3Layout);
        jDesktopPane3Layout.setHorizontalGroup(
            jDesktopPane3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel6, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jDesktopPane3Layout.setVerticalGroup(
            jDesktopPane3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDesktopPane3Layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 900, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jDesktopPane3, javax.swing.GroupLayout.Alignment.TRAILING))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 565, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jDesktopPane3, javax.swing.GroupLayout.Alignment.TRAILING))
        );

        jTabbedPane1.addTab("Đặt vé tàu hỏa", jPanel1);

        jDesktopPane2.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Serif", 0, 14)); // NOI18N
        jLabel1.setText("Thông tin khách hàng");

        jLabel2.setFont(new java.awt.Font("Serif", 0, 14)); // NOI18N
        jLabel2.setText("Họ tên           :");

        jLabel3.setFont(new java.awt.Font("Serif", 0, 14)); // NOI18N
        jLabel3.setText("Số điện thoại:");

        jLabel4.setFont(new java.awt.Font("Serif", 0, 14)); // NOI18N
        jLabel4.setText("Địa chỉ          :");

        lblusername.setFont(new java.awt.Font("Serif", 0, 14)); // NOI18N
        lblusername.setText("Tên đăng nhập :");

        lblPassword.setFont(new java.awt.Font("Serif", 0, 14)); // NOI18N
        lblPassword.setText("Mật khẩu         :");

        lblNewPassword.setFont(new java.awt.Font("Serif", 0, 14)); // NOI18N
        lblNewPassword.setText("Mật khẩu mới :");

        btnSignOut.setFont(new java.awt.Font("Serif", 0, 14)); // NOI18N
        btnSignOut.setText("Đăng xuất");
        btnSignOut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSignOutActionPerformed(evt);
            }
        });

        txtPassword.setFont(new java.awt.Font("Serif", 0, 14)); // NOI18N
        txtPassword.setText("jPasswordField1");

        txtNewPassword.setFont(new java.awt.Font("Serif", 0, 14)); // NOI18N
        txtNewPassword.setText("jPasswordField1");
        txtNewPassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNewPasswordActionPerformed(evt);
            }
        });

        txtUsername.setFont(new java.awt.Font("Serif", 0, 12)); // NOI18N
        txtUsername.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtUsernameActionPerformed(evt);
            }
        });

        txtFullname.setFont(new java.awt.Font("Serif", 0, 12)); // NOI18N
        txtFullname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFullnameActionPerformed(evt);
            }
        });

        btnEditInfo.setText("Đổi thông tin");

        btnEditPass.setText("Đổi mật khẩu");

        txtPhoneNumber.setFont(new java.awt.Font("Serif", 0, 12)); // NOI18N
        txtPhoneNumber.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPhoneNumberActionPerformed(evt);
            }
        });

        txtAddress.setFont(new java.awt.Font("Serif", 0, 12)); // NOI18N
        txtAddress.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAddressActionPerformed(evt);
            }
        });

        btnCancelEditPassword.setText("Hủy");
        btnCancelEditPassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelEditPasswordActionPerformed(evt);
            }
        });

        btnCancelEditInfo.setText("Hủy");
        btnCancelEditInfo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelEditInfoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnSignOut)
                        .addGap(45, 45, 45))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 85, Short.MAX_VALUE))
                                .addGap(39, 39, 39)
                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtFullname, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtPhoneNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtAddress, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addComponent(btnEditInfo)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnCancelEditInfo)))
                        .addGap(118, 118, 118)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addComponent(btnEditPass)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnCancelEditPassword))
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(lblusername, javax.swing.GroupLayout.DEFAULT_SIZE, 92, Short.MAX_VALUE)
                                    .addComponent(lblNewPassword, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(lblPassword, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(38, 38, 38)
                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtUsername)
                                    .addComponent(txtNewPassword, javax.swing.GroupLayout.DEFAULT_SIZE, 140, Short.MAX_VALUE)
                                    .addComponent(txtPassword))))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(btnSignOut))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtFullname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lblusername)
                        .addComponent(txtUsername, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblPassword)
                    .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtAddress, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtPhoneNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblNewPassword)
                    .addComponent(txtNewPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnEditPass)
                    .addComponent(btnEditInfo)
                    .addComponent(btnCancelEditPassword)
                    .addComponent(btnCancelEditInfo))
                .addContainerGap(18, Short.MAX_VALUE))
        );

        btnViewTicket.setFont(new java.awt.Font("Serif", 0, 14)); // NOI18N
        btnViewTicket.setText("Xem thông tin các vé đã đặt");
        btnViewTicket.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewTicketActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Serif", 0, 14)); // NOI18N
        jLabel5.setText("Từ ngày ");

        jLabel6.setFont(new java.awt.Font("Serif", 0, 14)); // NOI18N
        jLabel6.setText("Đến ngày");

        btnSearchTicket.setFont(new java.awt.Font("Serif", 0, 14)); // NOI18N
        btnSearchTicket.setText("Tìm kiếm");

        btnNextStartTime.setText(">");
        btnNextStartTime.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNextStartTimeActionPerformed(evt);
            }
        });

        txtEndTime.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEndTimeActionPerformed(evt);
            }
        });

        btnBackEndTime.setText("<");

        btnBackStartTime.setText("<");
        btnBackStartTime.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackStartTimeActionPerformed(evt);
            }
        });

        txtStartTime.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtStartTimeActionPerformed(evt);
            }
        });

        btnNextEndTime.setText(">");
        btnNextEndTime.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNextEndTimeActionPerformed(evt);
            }
        });

        tblTicketedCustomer.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Mã vé", "Mã tàu", "Ga khởi hành", "Ga đến", "Thời gian khởi hành", "Loại vé", "Giá vé"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, true, false, false, false, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane4.setViewportView(tblTicketedCustomer);
        if (tblTicketedCustomer.getColumnModel().getColumnCount() > 0) {
            tblTicketedCustomer.getColumnModel().getColumn(0).setPreferredWidth(30);
            tblTicketedCustomer.getColumnModel().getColumn(1).setPreferredWidth(30);
        }

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnViewTicket)
                .addGap(74, 74, 74)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnBackStartTime)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtStartTime, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnNextStartTime)
                .addGap(73, 73, 73)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnBackEndTime)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtEndTime, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnNextEndTime)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 53, Short.MAX_VALUE)
                .addComponent(btnSearchTicket)
                .addContainerGap())
            .addComponent(jScrollPane4)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnSearchTicket)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnViewTicket)
                        .addComponent(jLabel5)
                        .addComponent(jLabel6)
                        .addComponent(btnNextStartTime)
                        .addComponent(txtEndTime, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnBackEndTime)
                        .addComponent(btnBackStartTime)
                        .addComponent(txtStartTime, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnNextEndTime)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 328, Short.MAX_VALUE))
        );

        jDesktopPane2.setLayer(jPanel5, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane2.setLayer(jPanel2, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jDesktopPane2Layout = new javax.swing.GroupLayout(jDesktopPane2);
        jDesktopPane2.setLayout(jDesktopPane2Layout);
        jDesktopPane2Layout.setHorizontalGroup(
            jDesktopPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jDesktopPane2Layout.setVerticalGroup(
            jDesktopPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDesktopPane2Layout.createSequentialGroup()
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 900, Short.MAX_VALUE)
            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jDesktopPane2, javax.swing.GroupLayout.Alignment.TRAILING))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 565, Short.MAX_VALUE)
            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jDesktopPane2))
        );

        jTabbedPane1.addTab("Thông tin cá nhân", jPanel4);

        jDesktopPane1.setLayer(jTabbedPane1, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 900, Short.MAX_VALUE)
            .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 900, Short.MAX_VALUE))
        );
        jDesktopPane1Layout.setVerticalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 600, Short.MAX_VALUE)
            .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 600, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 900, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jDesktopPane1, javax.swing.GroupLayout.Alignment.TRAILING))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 600, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jDesktopPane1, javax.swing.GroupLayout.Alignment.TRAILING))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txtUsernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtUsernameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtUsernameActionPerformed

    private void txtFullnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFullnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFullnameActionPerformed

    private void txtPhoneNumberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPhoneNumberActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPhoneNumberActionPerformed

    private void txtAddressActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAddressActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAddressActionPerformed

    private void txtNewPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNewPasswordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNewPasswordActionPerformed

    private void btnCancelEditPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelEditPasswordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnCancelEditPasswordActionPerformed

    private void btnCancelEditInfoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelEditInfoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnCancelEditInfoActionPerformed

    private void btnViewTicketActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewTicketActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnViewTicketActionPerformed

    private void btnNextStartTimeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNextStartTimeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnNextStartTimeActionPerformed

    private void txtEndTimeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEndTimeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEndTimeActionPerformed

    private void txtStartTimeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtStartTimeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtStartTimeActionPerformed

    private void btnNextEndTimeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNextEndTimeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnNextEndTimeActionPerformed

    private void btnBackStartTimeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackStartTimeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnBackStartTimeActionPerformed

    private void cbbEndStationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbbEndStationActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbbEndStationActionPerformed

    private void btnSreachActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSreachActionPerformed

    }//GEN-LAST:event_btnSreachActionPerformed

    private void btnAddTicketActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddTicketActionPerformed
        
        int indexTrainRide;
        try {
            indexTrainRide = tblTrainRide.getSelectedRow();
        } catch (Exception e) {
            indexTrainRide = -1;
        }
        
        if(indexTrainRide == -1){
            JOptionPane.showMessageDialog(mainFrm, "Chưa chọn chuyến tàu, hãy thử lại");
        } 
        else {
            
            String seatType = String.valueOf(tblTrainRide.getValueAt(indexTrainRide, 5));
            seatType = "" + seatType.charAt(seatType.length() - 1);
            
            Ticket ticket = new Ticket("id",Integer.parseInt( String.valueOf(tblTrainRide.getValueAt(indexTrainRide, 6))), 
                                        trainRides.get(indexTrainRide), customer, (new Employee()), 
                                        Integer.parseInt(seatType));
            
            
            String idBranch = "";
            String strStartBranch = (String) cbbStartBranch.getSelectedItem();

            switch (strStartBranch) {
                case "Đà Nẵng" -> idBranch = "DN";
                case "Hà Nội" -> idBranch = "HN";
                case "Hải Phòng" -> idBranch = "HP";
                case "Hồ Chí Minh" -> idBranch = "HCM";
                default -> {
                }
            }
            
            (new ConfirmTicketFrm(ticket, idBranch,mainFrm)).setVisible(true);
            this.setVisible(false);
        }
  
    }//GEN-LAST:event_btnAddTicketActionPerformed

    private void cbbStartStationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbbStartStationActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbbStartStationActionPerformed

    private void cbbseatTypeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbbseatTypeActionPerformed
  
    }//GEN-LAST:event_cbbseatTypeActionPerformed

    private void cbbStartBranchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbbStartBranchActionPerformed
        String idBranch = "";
        String strStartBranch = (String) cbbStartBranch.getSelectedItem();
        
        switch (strStartBranch) {
            case "Đà Nẵng" -> idBranch = "DN";
            case "Hà Nội" -> idBranch = "HN";
            case "Hải Phòng" -> idBranch = "HP";
            case "Hồ Chí Minh" -> idBranch = "HCM";
            default -> {
            }
        }

        
        cbbStartStation.removeAllItems();
        
        for( int i = 0; i< stations.size(); i++){
            Station station = stations.get(i);
            
            if (station.getId().contains(idBranch)){
                cbbStartStation.addItem(station.getName().trim());
            }
        }
    }//GEN-LAST:event_cbbStartBranchActionPerformed

    private void cbbEndBranchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbbEndBranchActionPerformed
        String idBranch = "";
        String strEndBranch = (String) cbbEndBranch.getSelectedItem();
        
        switch (strEndBranch) {
            case "Đà Nẵng" -> idBranch = "DN";
            case "Hà Nội" -> idBranch = "HN";
            case "Hải Phòng" -> idBranch = "HP";
            case "Hồ Chí Minh" -> idBranch = "HCM";
            default -> {
            }
        }

        
        cbbEndStation.removeAllItems();
        
        for( int i = 0; i< stations.size(); i++){
            Station station = stations.get(i);
            
            if (station.getId().contains(idBranch)){
                cbbEndStation.addItem(station.getName().trim());
            }
        }
    }//GEN-LAST:event_cbbEndBranchActionPerformed

    private void btnSignOutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSignOutActionPerformed
        (new LoginFrm()).setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnSignOutActionPerformed

    
    
    /**
     * @param args the command line arguments
     */


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddTicket;
    private javax.swing.JButton btnBackEndTime;
    private javax.swing.JButton btnBackStartTime;
    private javax.swing.JButton btnCancelEditInfo;
    private javax.swing.JButton btnCancelEditPassword;
    private javax.swing.JButton btnEditInfo;
    private javax.swing.JButton btnEditPass;
    private javax.swing.JButton btnNextEndTime;
    private javax.swing.JButton btnNextStartTime;
    private javax.swing.JButton btnSearchTicket;
    private javax.swing.JButton btnSignOut;
    private javax.swing.JButton btnSreach;
    private javax.swing.JButton btnViewTicket;
    private javax.swing.JComboBox<String> cbbEndBranch;
    private javax.swing.JComboBox<String> cbbEndStation;
    private javax.swing.JComboBox<String> cbbStartBranch;
    private javax.swing.JComboBox<String> cbbStartStation;
    private javax.swing.JComboBox<String> cbbseatType;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JDesktopPane jDesktopPane2;
    private javax.swing.JDesktopPane jDesktopPane3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JLabel lblEndBranch;
    private javax.swing.JLabel lblNameCustomer;
    private javax.swing.JLabel lblNewPassword;
    private javax.swing.JLabel lblPassword;
    private javax.swing.JLabel lblStartBranch;
    private javax.swing.JLabel lblusername;
    private javax.swing.JTable tblTicketedCustomer;
    private javax.swing.JTable tblTrainRide;
    private javax.swing.JTextField txtAddress;
    private javax.swing.JTextField txtEndTime;
    private javax.swing.JTextField txtFullname;
    private javax.swing.JPasswordField txtNewPassword;
    private javax.swing.JPasswordField txtPassword;
    private javax.swing.JTextField txtPhoneNumber;
    private javax.swing.JTextField txtStartTime;
    private javax.swing.JTextField txtUsername;
    // End of variables declaration//GEN-END:variables

    @Override
    public void actionPerformed(ActionEvent e) {
        
        Object source = e.getSource();
        
        if (source == btnEditInfo){
            ActionbtnEditInfo();
        }
        
        if (source == btnCancelEditInfo){
            
            ActionbtnCancelEditInfo();
        }
        
        if (source == btnEditPass){
            ActionbtnEditPass();
        }
        
        if (source == btnCancelEditPassword){
            ActionbtnCancelEditPassword();
        }
        
        if (source == btnViewTicket){
            getTicketedCustomer();
        }
        
        if(source == btnSearchTicket){
            getTickedSearch();
        }
        
        if(source == btnBackStartTime){
            ActionbtnBackStartTime();
        }
        
        if (source == btnNextStartTime) {
            ActionbtnNextStartTime();
        }
        
        if (source == btnBackEndTime){
            ActionbtnBackEndTime();
        }
        
        if (source == btnNextEndTime){
            ActionbtnNextEndTime();
        }
            
        if (source == btnSreach) {
            ActionbtnSreach();
        }    
    }
    
    public void ActionbtnEditInfo(){
        String strEidtIfo = btnEditInfo.getText();
        if(strEidtIfo.equals("Đổi thông tin")){

            btnEditInfo.setText("Lưu thay đổi");

            btnCancelEditInfo.setVisible(true);

            txtFullname.setEditable(true);
            txtAddress.setEditable(true);
            txtPhoneNumber.setEditable(true);
            txtUsername.setEditable(true);

            lblPassword.setVisible(true);
            txtPassword.setVisible(true);
            txtPassword.setText("");
            txtPassword.setEditable(true);

            btnEditPass.setVisible(false);

        } 
        else {
            String password = String.valueOf(txtPassword.getPassword());

            if(password.equals(customer.getPassword())){

                String newFullname = txtFullname.getText().trim();
                String newPhoneNumer = txtPhoneNumber.getText().trim();
                String newAddress = txtAddress.getText().trim();
                String newUsername = txtUsername.getText().trim();

                Customer c = new Customer();

                c.setId(customer.getId());
                c.setFullname(newFullname);
                c.setPhoneNumber(newPhoneNumer);
                c.setAddress(newAddress);
                c.setUsername(newUsername);
                c.setPassword(customer.getPassword());


                CustomerDAO customerDAO = new CustomerDAO();
                String status = customerDAO.editCustomer(c);

                if(status.equals("success")){

                    JOptionPane.showMessageDialog(mainFrm, "Cập nhật thông tin thành công");
                    
                    customer = c;

                    btnEditInfo.setText("Đổi thông tin");

                    txtFullname.setText(newFullname);
                    txtAddress.setText(newAddress);
                    txtPhoneNumber.setText(newPhoneNumer);
                    txtUsername.setText(newUsername);

                    txtFullname.setEditable(false);
                    txtAddress.setEditable(false);
                    txtPhoneNumber.setEditable(false);
                    txtUsername.setEditable(false);

                    lblPassword.setVisible(false);
                    txtPassword.setVisible(false);
                    txtPassword.setEditable(false);

                    btnCancelEditInfo.setVisible(false);
                    
                    btnEditPass.setVisible(true);
                } 
                else {
                    JOptionPane.showMessageDialog(mainFrm, "Cập nhật thông tin thất bại.\nLỗi: " + status);
                    txtFullname.setText(customer.getFullname());
                    txtAddress.setText(customer.getAddress());
                    txtPhoneNumber.setText(customer.getPhoneNumber());
                    txtUsername.setText(customer.getUsername());


                }
            } 
            else{
                JOptionPane.showMessageDialog(mainFrm, "Mật khẩu không đúng");
            }

        }
    }
    
    public void ActionbtnCancelEditInfo(){
        txtFullname.setText(customer.getFullname());
        txtAddress.setText(customer.getAddress());
        txtPhoneNumber.setText(customer.getPhoneNumber());
        txtUsername.setText(customer.getUsername());

        btnEditInfo.setText("Đổi thông tin");

        txtFullname.setEditable(false);
        txtAddress.setEditable(false);
        txtPhoneNumber.setEditable(false);
        txtUsername.setEditable(false);

        lblPassword.setVisible(false);
        txtPassword.setVisible(false);
        txtPassword.setEditable(false);

        btnCancelEditInfo.setVisible(false);
        btnEditPass.setVisible(true);
    }
    
    public void ActionbtnEditPass(){
        
        String strbtnEditPass = btnEditPass.getText();
        
        if(strbtnEditPass.equals("Đổi mật khẩu")){
            
            btnEditPass.setText("Lưu thay đổi");
            btnCancelEditPassword.setVisible(true);
            btnEditInfo.setVisible(false);
            
            
            lblPassword.setVisible(true);
            lblNewPassword.setVisible(true);

            txtPassword.setVisible(true);
            txtPassword.setText("");
            txtPassword.setEditable(true);

            txtNewPassword.setVisible(true);
            txtNewPassword.setText("");
            txtNewPassword.setEditable(true);
          
        }
        else {
            
            String password = String.valueOf(txtPassword.getPassword());
            
            if(password.equals(customer.getPassword())){

                String newPassword = String.valueOf(txtNewPassword.getPassword());

                Customer c = new Customer();

                c.setId(customer.getId());
                c.setFullname(customer.getFullname());
                c.setPhoneNumber(customer.getPhoneNumber());
                c.setAddress(customer.getAddress());
                c.setUsername(customer.getUsername());
                c.setPassword(newPassword);


                CustomerDAO customerDAO = new CustomerDAO();
                String status = customerDAO.editCustomer(c); 
                if(status.equals("success")){
                    JOptionPane.showMessageDialog(mainFrm, " Cập nhật mật khẩu thành công ");
                    
                    btnEditPass.setText("Đổi mật khẩu");
                    btnCancelEditPassword.setVisible(false);
                    btnEditInfo.setVisible(true);

                    lblPassword.setVisible(false);
                    lblNewPassword.setVisible(false);

                    txtPassword.setVisible(false);
                    txtNewPassword.setVisible(false);
                    
                    btnEditInfo.setVisible(true);

                } else {
                    JOptionPane.showMessageDialog(mainFrm, "Cập nhật mật khẩu thất bại.\nLỗi: " + status);
                    txtPassword.setText("");
                    txtNewPassword.setText("");
                }
                    
            }
            else {
                JOptionPane.showMessageDialog(mainFrm, "Mật khẩu không đúng");
                txtPassword.setText("");
                txtNewPassword.setText("");
            }
        }
        
    }
            
    public void ActionbtnCancelEditPassword(){
        btnEditPass.setText("Đổi mật khẩu");
        btnCancelEditPassword.setVisible(false);
        btnEditInfo.setVisible(true);

        lblPassword.setVisible(false);
        lblNewPassword.setVisible(false);

        txtPassword.setVisible(false);
        txtNewPassword.setVisible(false);

        btnEditInfo.setVisible(true);
    }    

    public void getTicketedCustomer(){
        
//        btnViewTicket.setEnabled(false);
        jLabel5.setVisible(true);
        jLabel6.setVisible(true);
        btnSearchTicket.setVisible(true);
        
        btnBackStartTime.setVisible(true);
        txtStartTime.setVisible(true);
        btnNextStartTime.setVisible(true);
        
        btnBackEndTime.setVisible(true);
        txtEndTime.setVisible(true);
        btnNextEndTime.setVisible(true);
        
        startDate = LocalDate.now();
        endDate = LocalDate.now();
        
        txtStartTime.setText(String.valueOf(startDate));
        txtEndTime.setText(String.valueOf(endDate));
        
        TicketDAO ticketDAO = new TicketDAO();
        ArrayList<Ticket>  listTicketedCustomerFULL = ticketDAO.getListTicketedCustomer(customer.getId());
        listTicketedCustomer = listTicketedCustomerFULL;
        
        insertTickTable(listTicketedCustomer);        
    }
    
    public void getTickedSearch(){
        
        ArrayList<Ticket> listTicketedCustomerSearch = new ArrayList<>();

        
        for (int i = 0; i < listTicketedCustomer.size(); i++) {
            Ticket ticket = listTicketedCustomer.get(i);
            LocalDateTime departureTime = ticket.getTrainRide().getDepartureTime();

            DateTimeFormatter formatter = DateTimeFormatter.ofPattern("yyyy-MM-dd HH:mm:ss");
            String departureTimeString = departureTime.format(formatter);
            departureTimeString = departureTimeString.substring(0, departureTimeString.length() - 9);

            formatter = DateTimeFormatter.ofPattern("yyyy-MM-dd");
            LocalDate currentDate = LocalDate.parse(departureTimeString, formatter);
            
            
            if (startDate.compareTo(currentDate) <= 0 && endDate.compareTo(currentDate) >= 0) {
                listTicketedCustomerSearch.add(ticket);
            }
        }
        insertTickTable(listTicketedCustomerSearch);
    }
    
    public void ActionbtnBackStartTime (){
        startDate = startDate.minusDays(1);
        txtStartTime.setText(String.valueOf(startDate));
    }
    
    public void ActionbtnNextStartTime (){
        startDate = startDate.plusDays(1);
        txtStartTime.setText(String.valueOf(startDate));

    }
    
    public void ActionbtnBackEndTime (){
        endDate = endDate.minusDays(1);
        txtEndTime.setText(String.valueOf(endDate));

    }
    
    public void ActionbtnNextEndTime (){
        endDate = endDate.plusDays(1);
        txtEndTime.setText(String.valueOf(endDate));

    }
    
    public void ActionbtnSreach (){
        TrainRideDAO trainRideDAO = new TrainRideDAO();
        
        String startStation = (String) cbbStartStation.getSelectedItem();
        String endStation = (String) cbbEndStation.getSelectedItem();
        
        ArrayList<TrainRide> listtrainRides = trainRideDAO.getListTrainRide(startStation, endStation);
        
        trainRides = listtrainRides;

        
        if(listtrainRides.isEmpty()){
            JOptionPane.showMessageDialog(mainFrm, "Không có chuyến tàu nào phù hợp với tiêu chí");

        }
        
        
        String[][] data = new String[listtrainRides.size()][7];
        String[] columNames = {"Mã tàu", "Ga xuất phát", "Ga kết thúc", "Thời gian khởi hành", "Thời gian đến", "Loại vé" , "Giá vé"};
        
        for(int i = 0; i<listtrainRides.size(); i++){
            TrainRide trainRide = listtrainRides.get(i);
            data[i][0] = trainRide.getTrain().getId();
            data[i][1] = trainRide.getDepartureStation().getName();
            
            data[i][2] = trainRide.getDestinationStation().getName();
            
            LocalDateTime departureTime = trainRide.getDepartureTime();
            
            DateTimeFormatter formatter = DateTimeFormatter.ofPattern("yyyy-MM-dd HH:mm:ss");
            String departureTimeString = departureTime.format(formatter);
            data[i][3] = departureTimeString;
            
            LocalDateTime arivalTime = trainRide.getArrivalTime();
            String arivalTimeString = arivalTime.format(formatter);
            data[i][4] = arivalTimeString;
            
           
            String seatTypeString = (String) cbbseatType.getSelectedItem();
            data[i][5]  = seatTypeString;
            
            int seatType = (int) seatTypeString.charAt(seatTypeString.length() -1);
            data[i][6] = String.valueOf((int)(trainRide.getTicketPrice() * ( seatType == 1 ? 1: 1.5)));
        }
        
        DefaultTableModel dtm = new DefaultTableModel(data, columNames){
            
            @Override
            public boolean isCellEditable(int row, int column) {
               return false;
            }
        };
        
        tblTrainRide.setModel(dtm);
        tblTrainRide.getTableHeader().setReorderingAllowed(false);
    }
    
    public void insertTickTable(ArrayList<Ticket>  listTicketedCustomer){
        
        String[][] data = new String[listTicketedCustomer.size()][7];
        String[] columNames = {"Mã vé", "Mã tàu", "Ga khởi hành", "Ga đến", "Thời gian khởi hành", "Loại vé", "Giá vé"};
        
        for(int i = 0; i<listTicketedCustomer.size(); i++){
            Ticket ticket = listTicketedCustomer.get(i);
            data[i][0] = ticket.getId();
            data[i][1] = ticket.getTrainRide().getTrain().getId();
            data[i][2] = ticket.getTrainRide().getDepartureStation().getName();
            data[i][3] = ticket.getTrainRide().getDestinationStation().getName();
            
            LocalDateTime departureTime = ticket.getTrainRide().getDepartureTime();
            DateTimeFormatter formatter = DateTimeFormatter.ofPattern("yyyy-MM-dd HH:mm:ss");
            String departureTimeString = departureTime.format(formatter);

            data[i][4] = departureTimeString;
            data[i][5] = "Hạng " + ticket.getSeatType();
            data[i][6] = String.valueOf(ticket.getTotalAmount());
        }
        
        DefaultTableModel dtm = new DefaultTableModel(data, columNames){
            
            @Override
            public boolean isCellEditable(int row, int column) {
               return false;
            }
        };
        
        tblTicketedCustomer.setModel(dtm);
        tblTicketedCustomer.getTableHeader().setReorderingAllowed(false); 
    }  
    
    public void updateTicketedCustomer(Ticket ticket){
        if(listTicketedCustomer != null){
            listTicketedCustomer.add(ticket);
            getTickedSearch();
        }
    }    
}


